#!/usr/bin/env python
"""
Pipeline Orchestrator
======================
Runs all 3 pipelines (Alamsabi, organic+BIPIA, organic+self-injected) x 3 ablation
modes (normal, user_intent_only, context_only) — 9 runs total — each as
generate_embeddings.py -> train_evaluate_visualize.py, writing into its own
runs/{pipeline}/{mode}/{embeddings,results,figures}/ folder. After all 9 runs
complete, aggregates every run's full_evaluation_results.csv into one master
comparison table at runs/all_pipelines_summary.{csv,html}.
"""

import argparse
import subprocess
import sys
from pathlib import Path

import pandas as pd

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT_DIR = SCRIPT_DIR.parent
DATA_DIR = ROOT_DIR / "data"
RUNS_DIR = ROOT_DIR / "runs"

PIPELINES = {
    "pipeline1_alamsabi": DATA_DIR / "final_training_dataset.jsonl",
    "pipeline2_organic_bipia": DATA_DIR / "organic_bipia_dataset.jsonl",
    "pipeline3_organic_injected": DATA_DIR / "organic_injected_dataset.jsonl",
}
MODES = ["normal", "user_intent_only", "context_only"]


def make_limited_copy(src: Path, limit: int, dest: Path) -> Path:
    """Write the first `limit` rows of src to dest (for smoke testing)."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    with open(src, "r", encoding="utf-8") as fin, open(dest, "w", encoding="utf-8") as fout:
        for i, line in enumerate(fin):
            if i >= limit:
                break
            fout.write(line)
    return dest


def run_step(cmd: list[str], label: str):
    print(f"\n{'='*70}\n>>> {label}\n{'='*70}")
    print("   $", " ".join(str(c) for c in cmd))
    result = subprocess.run(cmd)
    if result.returncode != 0:
        raise RuntimeError(f"Step failed (exit {result.returncode}): {label}")


def aggregate_results(runs_dir: Path):
    frames = []
    for pipeline_key in PIPELINES:
        for mode in MODES:
            csv_path = runs_dir / pipeline_key / mode / "results" / "full_evaluation_results.csv"
            if not csv_path.is_file():
                print(f"  ⚠️ Missing results for {pipeline_key}/{mode}, skipping in aggregate.")
                continue
            df = pd.read_csv(csv_path)
            df.insert(0, "Pipeline", pipeline_key)
            df.insert(1, "Mode", mode)
            frames.append(df)

    if not frames:
        print("  ❌ No run results found to aggregate.")
        return

    summary = pd.concat(frames, ignore_index=True).sort_values(by="ROC-AUC", ascending=False).reset_index(drop=True)
    summary.to_csv(runs_dir / "all_pipelines_summary.csv", index=False)

    # --- HTML Report Export ---
    # Aggregated table of results across all 9 pipeline x ablation-mode runs.
    html_table = summary.to_html(index=False, float_format=lambda x: f"{x:.4f}")
    html_doc = (
        "<!-- Generated by src/run_all_pipelines.py -->\n"
        "<html><head><meta charset=\"utf-8\"><title>All Pipelines Summary</title>"
        "<style>body{font-family:sans-serif;margin:2rem;}"
        "table{border-collapse:collapse;width:100%;}"
        "th,td{border:1px solid #ccc;padding:6px 10px;text-align:right;}"
        "th{background:#f2f2f2;text-align:center;}</style></head>"
        f"<body><h2>All Pipelines Summary</h2>{html_table}</body></html>\n"
    )
    (runs_dir / "all_pipelines_summary.html").write_text(html_doc, encoding="utf-8")

    print(f"  ✔️ Master summary written to: {runs_dir / 'all_pipelines_summary.csv'}")
    print(f"  ✔️ Master summary written to: {runs_dir / 'all_pipelines_summary.html'}")


def main():
    parser = argparse.ArgumentParser(
        description="Run all 3 pipelines x 3 ablation modes and aggregate results.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument("--limit", type=int, default=None,
                         help="Truncate each dataset to this many rows first (for smoke testing).")
    parser.add_argument("--force", action="store_true",
                         help="Force regeneration of embeddings even if cached.")
    parser.add_argument("--models", type=str, default=None,
                         help="Comma-separated subset of embedding models to run (passed through to generate_embeddings.py).")
    parser.add_argument("--python", type=str, default=sys.executable,
                         help="Python interpreter to use for subprocess calls.")
    args = parser.parse_args()

    for pipeline_key, data_path in PIPELINES.items():
        if not data_path.is_file():
            print(f"⚠️ Skipping {pipeline_key}: dataset not found at {data_path}")
            continue

        run_data_path = data_path
        if args.limit:
            run_data_path = make_limited_copy(data_path, args.limit, RUNS_DIR / "_smoke_data" / f"{pipeline_key}.jsonl")

        for mode in MODES:
            run_dir = RUNS_DIR / pipeline_key / mode
            embed_dir = run_dir / "embeddings"
            results_dir = run_dir / "results"
            figures_dir = run_dir / "figures"

            gen_cmd = [
                args.python, str(SCRIPT_DIR / "generate_embeddings.py"),
                "--data", str(run_data_path),
                "--mode", mode,
                "--embed-dir", str(embed_dir),
            ]
            if args.force:
                gen_cmd.append("--force")
            if args.models:
                gen_cmd += ["--models", args.models]
            run_step(gen_cmd, f"{pipeline_key} / {mode} — generate_embeddings")

            eval_cmd = [
                args.python, str(SCRIPT_DIR / "train_evaluate_visualize.py"),
                "--data", str(run_data_path),
                "--embed-dir", str(embed_dir),
                "--results-dir", str(results_dir),
                "--figures-dir", str(figures_dir),
            ]
            run_step(eval_cmd, f"{pipeline_key} / {mode} — train_evaluate_visualize")

    print(f"\n{'='*70}\n>>> Aggregating results across all runs\n{'='*70}")
    aggregate_results(RUNS_DIR)

    print("\n🎉🎉🎉 All pipelines completed! 🎉🎉🎉")


if __name__ == "__main__":
    main()
